### ISSUE TITLE
CI: Open an issue if state drift is detected

### ISSUE THREAD

**Issue by mircea-pavel-anton** [mirceanton/mikrotik-terraform#44]
I don't necessarily want to continuously reconcile this repo, gitops-style, on a give loop/period. I do, however, want to be notified when configuration drift happens.

Ideally, I would like a workflow that runs `terraform plan` on a schedule, and if drift is detected, open a GitHub issue in this repo to let me know.

**Comment by mircea-pavel-anton** [comment]
Something along the lines of:

```yaml
name: Terraform Drift Detection

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: "0 0 * * *"

jobs:
  terraform-drift:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -detailed-exitcode -out=tfplan || echo "PLAN_EXIT=$?" >> $GITHUB_ENV

      - name: Check for Drift
        id: check
        run: echo "DRIFT_DETECTED=$([ $PLAN_EXIT -eq 2 ] && echo true || echo false)" >> $GITHUB_ENV

      - name: Create GitHub Issue
        if: env.DRIFT_DETECTED == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_TITLE="Terraform Drift Detected"
          ISSUE_BODY="Terraform detected configuration drift. Run \`terraform apply\` to reconcile changes."
          
          # Check if an issue already exists
          EXISTING_ISSUE=$(gh issue list --state=open --search "$ISSUE_TITLE" --json number --jq '.[0].number')

          if [ -z "$EXISTING_ISSUE" ]; then
            gh issue create --title "$ISSUE_TITLE" --body "$ISSUE_BODY"
          else
            gh issue comment "$EXISTING_ISSUE" --body "Drift detected again. Review and apply necessary changes."
          fi

```
